#-------------------------------------------------------------------------
# Copyright(C) 2022 Intel Corporation.
# SPDX-License-Identifier: MIT
#--------------------------------------------------------------------------

FROM ubuntu:18.04

RUN apt update; \ 
    apt install -y software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt install -y python3.8

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1; \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2;

RUN apt install -y python3-pip && python3 -m pip install --upgrade pip
 
RUN pip install torch-ort-infer[openvino]

RUN pip install wget pandas transformers pillow torchvision

# RUN python -m torch_ort.configure